AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/geohash.rb'
    - 'lib/manager/geo.rb'
    - 'bin/spring'
    - 'Gemfile'
    - 'spec/*.rb'
    - 'config/puma.rb'
  TargetRubyVersion: 2.6.3

  Style/Documentation:
    Enabled: false