version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/my_app
      - public-data:/my_app/public
      - tmp-data:/my_app/tmp
      - log-data:/my_app/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3316:3306"
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/my_app/public
      - tmp-data:/my_app/tmp
    ports:
      - "3000:80"
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
