version: '3'
services:
  app: &app_base
    build:
      context: .
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_app_development
      DATABASE_HOST: db
    stdin_open: true
    tty: true
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/my_app
      - public-data:/my_app/public
      - tmp-data:/my_app/tmp
      - log-data:/my_app/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_app_development
      DATABASE_HOST: db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3316:3306"
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/my_app/public
      - tmp-data:/my_app/tmp
    ports:
      - "3000:80"
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
