default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'app' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'db_root_password' } %>
  host: <%= ENV.fetch('DATABASE_PORT') { 'db' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test
